spring.application.name=core-api

server.port=8081
server.servlet.context-path=/api/v2

server.error.include-stacktrace=never

spring.config.import=optional:file:.env[.properties]

# =========================
# CONFIG DB
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# SUPABASE JWT
# =========================
supabase.jwt.issuer=https://${SUPABASE_PROJECT_ID}.supabase.co/auth/v1
supabase.jwt.jwk-set-uri=https://${SUPABASE_PROJECT_ID}.supabase.co/auth/v1/.well-known/jwks.json

# =========================
# FLYWAY (disabled - migrations are test-only)
# =========================
spring.flyway.enabled=false

# =========================
# JPA
# =========================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jackson.property-naming-strategy=SNAKE_CASE

# logging.level.com.zaxxer.hikari=DEBUG
# logging.level.org.springframework.security=DEBUG

# =========================
# ASAAS
# =========================
asaas.api-key=${ASAAS_API_KEY}
asaas.environment=${ASAAS_ENVIRONMENT:PRODUCTION}
asaas.webhook-token=${ASAAS_WEBHOOK_TOKEN}
