-- H2 enum types (simulates PostgreSQL named enums)
CREATE DOMAIN IF NOT EXISTS age_group_enum AS VARCHAR(10) CHECK (VALUE IN ('BABY', 'CHILD', 'ADULT'));
CREATE DOMAIN IF NOT EXISTS guest_status_enum AS VARCHAR(10) CHECK (VALUE IN ('CONFIRMED', 'DECLINED', 'PENDING'));
CREATE DOMAIN IF NOT EXISTS user_role_enum AS VARCHAR(10) CHECK (VALUE IN ('COUPLE', 'ADMIN'));
CREATE DOMAIN IF NOT EXISTS order_status_enum AS VARCHAR(10) CHECK (VALUE IN ('PENDING', 'PAID', 'FAILED', 'EXPIRED'));
CREATE DOMAIN IF NOT EXISTS transaction_status_enum AS VARCHAR(10) CHECK (VALUE IN ('PENDING', 'COMPLETED', 'FAILED'));
CREATE DOMAIN IF NOT EXISTS message_type_enum AS VARCHAR(10) CHECK (VALUE IN ('GIFT', 'RSVP', 'GENERAL'));
