DROP TABLE IF EXISTS payment_configs;
DROP DOMAIN IF EXISTS payment_env_enum;

CREATE TABLE wallets (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    pix_key VARCHAR(255),
    balance INTEGER NOT NULL DEFAULT 0,
    fee INTEGER NOT NULL DEFAULT 500,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    wedding_id UUID NOT NULL UNIQUE,
    CONSTRAINT fk_wallet_wedding FOREIGN KEY (wedding_id) REFERENCES weddings(id) ON DELETE CASCADE
);
